spring:
  application:
    name: demo
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://172.17.0.2:5432/GerenciamentoSetor
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    show-sql: false

server:
  port: 8080
